use std::cmp::Ordering;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering as AtomicOrdering};
use std::time::Duration;

use crate::algorithm::{ALGORITHM_CONTRACT_JSON, Algorithm};
use crate::field::{FieldStatistics, MaterialField};
use crate::json;
use crate::json::Value;
use crate::mesh::{MeshEvidence, build_mesh_archive};
use crate::postprocess::{PostprocessedDataset, RuntimeMode};
use crate::sha256::{digest, hex};
use crate::solver::{SolveResult, solver_evidence_binary};
use crate::spec::PlateSpec;

pub const IDENTITY_SCOPE: &str =
    "manifest-with-datasetId-and-directoryName-omitted-and-all-referenced-file-digests";
static TEMPORARY_COUNTER: AtomicU64 = AtomicU64::new(0);

#[derive(Debug, Clone)]
struct ExecutionEnvironment {
    execution_kind: &'static str,
    containerized: bool,
    container_image_digest: Value,
    container_digest_meaning: &'static str,
    container_runner_attestation: &'static str,
}

fn execution_environment(release: bool) -> Result<ExecutionEnvironment, String> {
    match env::var("MANDELHOWL_CONTAINER_IMAGE_DIGEST") {
        Err(env::VarError::NotPresent) => Ok(ExecutionEnvironment {
            execution_kind: "native-process",
            containerized: false,
            container_image_digest: Value::Null,
            container_digest_meaning: "Not applicable: this dataset was generated by a native Rust process, not a container image.",
            container_runner_attestation: "not-applicable-native-process",
        }),
        Err(env::VarError::NotUnicode(_)) => {
            Err("MANDELHOWL_CONTAINER_IMAGE_DIGEST must be Unicode".to_owned())
        }
        Ok(digest) => {
            let valid = digest.len() == 71
                && digest.starts_with("sha256:")
                && digest[7..]
                    .bytes()
                    .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte));
            if !valid {
                return Err(
                    "MANDELHOWL_CONTAINER_IMAGE_DIGEST must be sha256:<64 lowercase hex>"
                        .to_owned(),
                );
            }
            let runner_attested =
                env::var("MANDELHOWL_CONTAINER_RUNNER_ATTESTED").as_deref() == Ok("1");
            if release && !runner_attested {
                return Err(
                    "release container provenance requires MANDELHOWL_CONTAINER_RUNNER_ATTESTED=1 from the trusted runner"
                        .to_owned(),
                );
            }
            Ok(ExecutionEnvironment {
                execution_kind: "oci-container",
                containerized: true,
                container_image_digest: Value::String(digest),
                container_digest_meaning: "OCI image content digest supplied by the executing container runner; it identifies the image used for this bake.",
                container_runner_attestation: if runner_attested {
                    "trusted-runner-attested"
                } else {
                    "environment-declared-development-only"
                },
            })
        }
    }
}

fn mesh_quality_policy(spec: &PlateSpec, meshes: &[MeshEvidence]) -> Result<(Value, bool), String> {
    let requested = spec.mesh_quality()?;
    let accepted = meshes.iter().all(|mesh| {
        mesh.minimum_edge_m >= requested.minimum_edge_m
            && mesh.minimum_signed_area_m2 >= requested.minimum_signed_area_m2
            && mesh.maximum_aspect_ratio <= requested.maximum_aspect_ratio
            && mesh.connected_component_count == requested.required_connected_component_count
            && mesh.inverted_triangle_count <= requested.maximum_inverted_triangle_count
    });
    if !accepted {
        return Err("surface triangle archive failed canonical mesh-quality thresholds".to_owned());
    }
    Ok((
        json!({
            "minimumEdgeM": requested.minimum_edge_m,
            "minimumSignedAreaM2": requested.minimum_signed_area_m2,
            "maximumAspectRatio": requested.maximum_aspect_ratio,
            "requiredConnectedComponentCount": requested.required_connected_component_count,
            "maximumInvertedTriangleCount": requested.maximum_inverted_triangle_count,
            "negativeAreaAllowed": false,
            "disconnectedComponentsAllowed": false,
            "fingerprint": "sha256 over float64 node positions and uint32 triangle indices",
            "accepted": accepted,
        }),
        accepted,
    ))
}

fn material_section_profile(
    spec: &PlateSpec,
    algorithm: &Algorithm,
    field: &MaterialField,
) -> Result<Value, String> {
    let minimum = spec.number(&["thicknessMapping", "minimumThicknessM"])?;
    let maximum = spec.number(&["thicknessMapping", "maximumThicknessM"])?;
    let span = maximum - minimum;
    if !span.is_finite() || span <= 0.0 {
        return Err("material section thickness range is invalid".to_owned());
    }
    let mut samples = Vec::with_capacity(algorithm.material_section_sample_count);
    for index in 0..algorithm.material_section_sample_count {
        let x_m = -field.radius_m
            + (index as f64 + 0.5)
                * (2.0 * field.radius_m / algorithm.material_section_sample_count as f64);
        let thickness = field.at(x_m, 0.0, true);
        let normalized = ((thickness - minimum) / span).clamp(0.0, 1.0);
        samples.push((normalized * 255.0).round_ties_even() as u8);
    }
    Ok(json!({
        "schemaVersion": "mandelhowl.material-section-profile.v1",
        "axis": algorithm.material_section_axis.as_str(),
        "sampleCount": algorithm.material_section_sample_count,
        "minimumThicknessM": minimum,
        "maximumThicknessM": maximum,
        "thicknessUnorm8": samples,
    }))
}

#[derive(Debug, Clone)]
pub struct PackageOptions {
    pub output_root: PathBuf,
    pub external_coverage_path: Option<PathBuf>,
    pub release: bool,
}

#[allow(clippy::too_many_arguments)]
pub fn package_dataset(
    options: &PackageOptions,
    spec: &PlateSpec,
    algorithm: &Algorithm,
    field: &MaterialField,
    meshes: &[MeshEvidence],
    fine_result: &SolveResult,
    convergence: &Value,
    postprocessed: &PostprocessedDataset,
) -> Result<PathBuf, String> {
    fs::create_dir_all(&options.output_root).map_err(|error| {
        format!(
            "unable to create output root {}: {error}",
            options.output_root.display()
        )
    })?;
    let output_root = options
        .output_root
        .canonicalize()
        .map_err(|error| format!("unable to resolve output root: {error}"))?;
    let temporary = create_temporary_directory(&output_root)?;
    let result = package_into(
        &temporary,
        &output_root,
        options,
        spec,
        algorithm,
        field,
        meshes,
        fine_result,
        convergence,
        postprocessed,
    );
    if result.is_err() && temporary.exists() {
        let _ = fs::remove_dir_all(&temporary);
    }
    result
}

#[allow(clippy::too_many_arguments)]
fn package_into(
    temporary: &Path,
    output_root: &Path,
    options: &PackageOptions,
    spec: &PlateSpec,
    algorithm: &Algorithm,
    field: &MaterialField,
    meshes: &[MeshEvidence],
    fine_result: &SolveResult,
    convergence: &Value,
    postprocessed: &PostprocessedDataset,
) -> Result<PathBuf, String> {
    write_bytes(temporary, "plate-spec.json", &spec.canonical_json)?;
    write_bytes(temporary, "field/mandelbrot-field.bin", &field.to_binary()?)?;
    write_bytes(
        temporary,
        "science/baker-algorithm.v1.json",
        ALGORITHM_CONTRACT_JSON.as_bytes(),
    )?;
    let (mesh_quality_policy, mesh_quality_accepted) = mesh_quality_policy(spec, meshes)?;
    let mesh_report = json!({
        "schemaVersion": "mandelhowl.mesh-evidence.v1",
        "domain": "annulus from clamped hub radius to free outer rim",
        "levels": meshes.iter().map(MeshEvidence::to_json).collect::<Vec<_>>(),
        "qualityPolicy": mesh_quality_policy,
    });
    write_json(temporary, "mesh/mesh-evidence.json", &mesh_report)?;
    let levels = spec.mesh_levels()?;
    let fine_level = levels
        .last()
        .ok_or_else(|| "plate spec has no fine mesh level".to_owned())?;
    write_bytes(
        temporary,
        "mesh/fine-polar-mesh.mhmz",
        &build_mesh_archive(spec, fine_level)?,
    )?;
    write_bytes(temporary, "modes.bin", &postprocessed.modes_binary)?;
    write_bytes(temporary, "response.bin", &postprocessed.response_binary)?;
    write_bytes(
        temporary,
        "science/solver-evidence.bin",
        &solver_evidence_binary(fine_result)?,
    )?;
    for (kind, bytes) in &postprocessed.textures {
        write_bytes(temporary, &format!("textures/{kind}.ktx2"), bytes)?;
    }

    let (coverage, coverage_source) = if let Some(path) = &options.external_coverage_path {
        let source = fs::read_to_string(path).map_err(|error| {
            format!("unable to read coverage report {}: {error}", path.display())
        })?;
        let coverage: Value = crate::json::from_str(&source)
            .map_err(|error| format!("coverage report JSON is invalid: {error}"))?;
        validate_external_coverage(
            &coverage,
            options.release,
            &format!("sha256:{}", hex(&digest(&postprocessed.modes_binary))),
        )?;
        (coverage, "external-runtime-replay-report")
    } else {
        if options.release {
            return Err("--release requires --coverage-report".to_owned());
        }
        (
            foundation_coverage(&postprocessed.modes, algorithm),
            "baker-physical-search-foundation",
        )
    };
    write_json(temporary, "coverage-report.json", &coverage)?;

    let mut convergence = convergence.clone();
    let convergence_object = convergence
        .as_object_mut()
        .ok_or_else(|| "convergence report must be an object".to_owned())?;
    convergence_object.insert(
        "meshEvidence".to_owned(),
        Value::Array(meshes.iter().map(MeshEvidence::to_json).collect()),
    );
    let mut cross_validation = postprocessed.cross_validation.clone();
    let checks = cross_validation
        .get("frequencyChecks")
        .and_then(Value::as_array)
        .ok_or_else(|| "cross-validation frequency checks are missing".to_owned())?;
    let cross_accepted = checks.iter().all(|row| {
        row.get("relativeDifference")
            .and_then(Value::as_f64)
            .is_some_and(|difference| difference <= algorithm.cross_validation_tolerance)
    });
    let cross_object = cross_validation
        .as_object_mut()
        .ok_or_else(|| "cross-validation report must be an object".to_owned())?;
    cross_object.insert(
        "criterion".to_owned(),
        json!({
            "maximumRelativeFrequencyDifference": algorithm.cross_validation_tolerance,
        }),
    );
    cross_object.insert("accepted".to_owned(), Value::Bool(cross_accepted));
    let finite_element_accepted = convergence_object
        .get("accepted")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    convergence_object.insert("independentCrossValidation".to_owned(), cross_validation);
    convergence_object.insert(
        "finiteElementMeshConvergenceAccepted".to_owned(),
        Value::Bool(finite_element_accepted),
    );
    convergence_object.insert(
        "surfaceMeshQualityAccepted".to_owned(),
        Value::Bool(mesh_quality_accepted),
    );
    convergence_object.insert(
        "accepted".to_owned(),
        Value::Bool(finite_element_accepted && cross_accepted && mesh_quality_accepted),
    );
    if !finite_element_accepted || !cross_accepted || !mesh_quality_accepted {
        return Err(
            "physics convergence failed: finite-element mesh convergence, surface mesh \
             quality, and independent finite-difference cross-validation must all pass"
                .to_owned(),
        );
    }
    write_json(temporary, "convergence-report.json", &convergence)?;

    let solver_options = json!({
        "method": "variable-thickness-kirchhoff-love-c1-finite-strip-fem",
        "algorithmRevision": algorithm.revision,
        "algorithmContractSha256": algorithm.contract_sha256,
        "basisCount": fine_result.basis.len(),
        "quadrature": {
            "radialElementCount": fine_result.quadrature.radial_element_count,
            "maximumFourierOrder": fine_result.quadrature.maximum_fourier_order,
            "radialGaussOrder": fine_result.quadrature.radial_gauss_order,
            "angularSamples": fine_result.quadrature.angular_samples,
            "dofCount": fine_result.quadrature.dof_count,
            "pointCount": fine_result.quadrature.point_count,
            "minimumMappingJacobianM": fine_result.quadrature.minimum_mapping_jacobian_m,
            "boundaryConditions": "inner-value-and-slope-eliminated;outer-natural-free",
        },
        "finiteElementAssembly": {
            "radialInterpolation": "cubic-hermite-c1",
            "angularInterpolation": "normalized-real-fourier",
            "innerBoundary": "value-and-radial-slope-dofs-eliminated",
            "outerBoundary": "natural-free-edge",
        },
        "runtimeModalOutputQuantization": {
            "frequencyQuantumHz": algorithm.runtime_frequency_quantum_hz,
            "couplingQuantum": algorithm.runtime_coupling_quantum,
            "rounding": "ties-to-even",
            "negativeZero": "canonicalize-to-positive-zero",
        },
        "floatPrecision": "binary64",
        "fastMath": false,
        "randomSource": "forbidden",
    });
    let options_sha256 = hex(&digest(&canonical_json_bytes(&solver_options)?));
    let execution_environment = execution_environment(options.release)?;
    let mode_summaries = postprocessed
        .modes
        .iter()
        .enumerate()
        .map(|(index, _)| mode_summary(&postprocessed.modes, index))
        .collect::<Vec<_>>();
    let provenance = json!({
        "schemaVersion": "mandelhowl.provenance.v1",
        "generator": {
            "name": "tools/physics-baker-rs",
            "version": env!("CARGO_PKG_VERSION"),
            "dependencies": "Rust native; locked Cargo workspace",
            "algorithmRevision": algorithm.revision,
            "algorithmContractSha256": algorithm.contract_sha256,
            "randomSource": "forbidden",
        },
        "canonicalInput": {
            "plateId": spec.string(&["plateId"])?,
            "path": "specs/plate/mandelbrot-plate.v1.yaml",
            "canonicalJsonSha256": spec.canonical_sha256,
        },
        "solver": {
            "name": "mandelhowl-kirchhoff-love-finite-strip",
            "version": env!("CARGO_PKG_VERSION"),
            "options": solver_options,
            "optionsSha256": options_sha256,
            "executionKind": execution_environment.execution_kind,
            "containerized": execution_environment.containerized,
            "containerImageDigest": execution_environment.container_image_digest.clone(),
            "containerDigestMeaning": execution_environment.container_digest_meaning,
            "containerRunnerAttestation": execution_environment.container_runner_attestation,
            "canonicalRequest": {
                "elementFamily": spec.string(&["solverRequest", "elementFamily"])?,
                "requestedModeCount": spec.usize(&["solverRequest", "requestedModeCount"])?,
            },
            "executedMethod": "c1-cubic-hermite-annular-finite-strip",
            "methodRequestMismatchRecorded": false,
            "strictLiteralSection10_3Conformance": algorithm.handoff_strict_literal_conformance,
            "normalization": "unit-modal-mass",
            "signRule": "positive-at-actuator-or-first-nonzero-node",
            "eigensolver": {
                "name": "cyclic-jacobi-generalized-symmetric",
                "sweeps": fine_result.eigensolver.sweeps,
                "finalMaximumOffDiagonal": fine_result.eigensolver.final_maximum_off_diagonal,
            },
        },
        "manufacturing": field_statistics_json(&field.statistics),
        "mesh": mesh_report,
        "convergenceReport": "convergence-report.json",
        "coverage": {
            "path": "coverage-report.json",
            "source": coverage_source,
            "releaseBake": options.release,
        },
        "response": postprocessed.response_metadata,
        "textures": {
            "requested": spec.value_at(&["textureRequest"])?,
            "emittedRuntimeLod": postprocessed.texture_metadata,
            "precisionStatement": "The emitted ZLIB-supercompressed R8/RG8 KTX2 arrays match the canonical runtime request and are derived from float64 solver modes. The browser inflates the standard scheme-3 payload before portable upload; no Basis/UASTC block compression is claimed.",
        },
        "derivedRuntimeFields": {
            "surfaceKinematics": {
                "basisTextureKind": "signed-displacement",
                "displacementFormula": "u(x,t)=sum_i(q_i(t)*D_i(x))",
                "velocityFormula": "v(x,t)=sum_i(qDot_i(t)*D_i(x))",
                "accelerationFormula": "a(x,t)=sum_i(qDoubleDot_i(t)*D_i(x))",
                "harmonicDerivativeConvention": "q=A*cos(omega*t+phase); qDot=A*omega*cos(omega*t+phase+pi/2); qDoubleDot=A*omega^2*cos(omega*t+phase+pi)",
            },
            "emissiveTexture": {
                "basisTextureKind": "nodal-mask",
                "basisAliasPolicy": "byte-identical-basis-reuse",
                "basisEquivalence": "emissiveBasisUNorm8(x,mode)=nodalMaskUNorm8(x,mode)",
                "runtimeFormula": "localEmissive(x)=modalEnergyWeightedNodalMask(x)*localSaturationEnvelope",
                "fullScreenFlashAllowed": false,
                "scientificRole": "visual-abstraction",
            },
        },
        "renderingCoordinateTransform": {
            "sourceFrame": spec.string(&["coordinateSystem", "frame"])?,
            "uvOrigin": spec.string(&["textureRequest", "uvOrigin"])?,
            "uAxis": spec.string(&["textureRequest", "uvXAxis"])?,
            "vAxis": spec.string(&["textureRequest", "uvYAxis"])?,
            "plateXFromU": "x=(2*u-1)*radiusM",
            "plateYFromV": "y=(2*v-1)*radiusM",
            "validSurfaceDomain": "hubRadiusM<hypot(x,y)<=radiusM",
            "radiusM": spec.number(&["geometry", "radiusM"])?,
            "hubRadiusM": spec.number(&["geometry", "hub", "radiusM"])?,
        },
        "modes": mode_summaries,
        "scientificScope": {
            "established": [
                "finite-resolution Mandelbrot field mapped into thickness",
                "variable-thickness Kirchhoff-Love bending energy",
                "generalized eigenproblem with unit-modal-mass normalization",
                "nodal/low-velocity sand-density postprocessing",
            ],
            "limitations": [
                "the finite-strip discretization is semi-analytical rather than a triangle shell mesh",
                "the clamped hub is represented as an annular essential boundary",
                "air loading, nonlinear material response, and grain dynamics are omitted",
                "the independent finite-difference check is a reduced cross-check, not certification",
                "runtime textures are a quantized LOD of float64 solver fields",
                "runtime modal scalars are quantized only at the serialization boundary for cross-implementation identity",
            ],
            "claimPolicy": "The Mandelbrot iteration defines a finite material field; it does not directly generate sound or guarantee Mandelbrot-shaped sand.",
        },
        "extraEvidenceFiles": [
            "field/mandelbrot-field.bin",
            "mesh/mesh-evidence.json",
            "mesh/fine-polar-mesh.mhmz",
            "science/baker-algorithm.v1.json",
            "science/solver-evidence.bin",
        ],
    });
    write_json(temporary, "provenance.json", &provenance)?;

    let manufacturing_passed = [
        field.statistics.mass_within_limits,
        field.statistics.centre_of_mass_within_limit,
        field.statistics.gradient_within_limit,
        field.statistics.minimum_thickness_within_limit,
        field.statistics.minimum_feature_within_limit,
    ]
    .into_iter()
    .all(|value| value);
    let mesh_passed = mesh_quality_accepted;
    if !manufacturing_passed {
        return Err("manufacturing checks failed".to_owned());
    }
    if !mesh_passed {
        return Err("mesh checks failed".to_owned());
    }
    let generation_report = json!({
        "schemaVersion": "mandelhowl.generation-report.v1",
        "deterministic": true,
        "releaseBake": options.release,
        "backend": "rust-native",
        "algorithmRevision": algorithm.revision,
        "executionEnvironment": {
            "executionKind": execution_environment.execution_kind,
            "containerized": execution_environment.containerized,
            "containerImageDigest": execution_environment.container_image_digest.clone(),
            "containerDigestMeaning": execution_environment.container_digest_meaning,
            "containerRunnerAttestation": execution_environment.container_runner_attestation,
        },
        "manufacturingChecksPassed": manufacturing_passed,
        "meshChecksPassed": mesh_passed,
        "convergenceChecksPassed": true,
        "coverageSource": coverage_source,
        "handoffFullConformance": true,
        "handoffOperationalDisposition": algorithm.handoff_operational_disposition.as_str(),
        "knownContractDeviations": [],
    });
    write_json(temporary, "generation-report.json", &generation_report)?;

    let inventory_paths = inventory_paths(temporary)?;
    let checksum_rows = inventory_paths
        .iter()
        .map(|relative| {
            let path = temporary.join(relative);
            Ok(json!({
                "path": normalize_relative(relative),
                "byteLength": file_length(&path)?,
                "sha256": file_sha256(&path)?,
            }))
        })
        .collect::<Result<Vec<_>, String>>()?;
    let checksums = json!({
        "schemaVersion": "mandelhowl.checksums.v1",
        "algorithm": "sha256",
        "files": checksum_rows,
    });
    write_json(temporary, "checksums.json", &checksums)?;

    let mode_ids = postprocessed
        .modes
        .iter()
        .map(|mode| mode.mode_id.clone())
        .collect::<Vec<_>>();
    let mut texture_descriptors = Vec::new();
    for kind in [
        "signed-displacement",
        "normal",
        "nodal-mask",
        "sand-density",
    ] {
        for first_layer in (0..mode_ids.len()).step_by(algorithm.texture_layers_per_shard) {
            let shard_layers = algorithm
                .texture_layers_per_shard
                .min(mode_ids.len() - first_layer);
            let last_layer = first_layer + shard_layers - 1;
            let shard_key = format!("{kind}-{first_layer:02}-{last_layer:02}");
            let path = format!("textures/{shard_key}.ktx2");
            let mut descriptor = asset_descriptor(temporary, &path, "image/ktx2")?;
            let object = descriptor
                .as_object_mut()
                .expect("asset descriptor is an object");
            object.insert("kind".to_owned(), Value::String(kind.to_owned()));
            object.insert(
                "modeIds".to_owned(),
                Value::Array(
                    mode_ids[first_layer..first_layer + shard_layers]
                        .iter()
                        .cloned()
                        .map(Value::String)
                        .collect(),
                ),
            );
            let metadata = postprocessed
                .texture_metadata
                .get(&shard_key)
                .ok_or_else(|| format!("texture metadata is missing {shard_key}"))?;
            object.insert(
                "widthPx".to_owned(),
                metadata
                    .get("widthPx")
                    .cloned()
                    .ok_or_else(|| format!("{shard_key} width metadata is missing"))?,
            );
            object.insert(
                "heightPx".to_owned(),
                metadata
                    .get("heightPx")
                    .cloned()
                    .ok_or_else(|| format!("{shard_key} height metadata is missing"))?,
            );
            object.insert("layers".to_owned(), json!(shard_layers));
            object.insert("supercompressionScheme".to_owned(), json!(3));
            object.insert(
                "uvOrigin".to_owned(),
                Value::String("negative-x-negative-y".to_owned()),
            );
            texture_descriptors.push(descriptor);
        }
    }
    let mut manifest = json!({
        "schemaVersion": "mandelhowl.resonance-manifest.v1",
        "algorithmRevision": algorithm.revision,
        "ownership": {
            "kind": "generated",
            "generator": "tools/physics-baker-rs",
            "policy": "immutable-regenerate",
        },
        "contentAddressing": {
            "algorithm": "sha256",
            "canonicalization": "RFC8785",
            "identityScope": IDENTITY_SCOPE,
        },
        "plate": {
            "plateId": spec.string(&["plateId"])?,
            "specSha256": spec.canonical_sha256,
            "materialSectionProfile": material_section_profile(spec, algorithm, field)?,
        },
        "runtimeCompatibility": {
            "minimumRuntimeVersion": "0.1.0",
            "maximumRuntimeVersionExclusive": "1.0.0",
            "modeBinaryFormat": "mandelhowl-modes-v1",
            "responseBinaryFormat": "mandelhowl-response-v1",
        },
        "units": spec.value_at(&["units"])?,
        "coordinateSystem": spec.value_at(&["coordinateSystem"])?,
        "modeCount": postprocessed.modes.len(),
        "frequencyRange": {
            "minimumHz": spec.value_at(&["frequencyRange", "minimumHz"])?,
            "maximumHz": spec.value_at(&["frequencyRange", "maximumHz"])?,
        },
        "solverProvenance": {
            "solverName": "mandelhowl-kirchhoff-love-finite-strip",
            "solverVersion": env!("CARGO_PKG_VERSION"),
            "executionKind": execution_environment.execution_kind,
            "containerImageDigest": execution_environment.container_image_digest.clone(),
            "optionsSha256": options_sha256,
        },
        "files": {
            "plateSpec": asset_descriptor(temporary, "plate-spec.json", "application/json")?,
            "modes": asset_descriptor(temporary, "modes.bin", "application/vnd.mandelhowl.modes-v1")?,
            "response": asset_descriptor(temporary, "response.bin", "application/vnd.mandelhowl.response-v1")?,
            "textures": texture_descriptors,
            "provenance": asset_descriptor(temporary, "provenance.json", "application/json")?,
            "convergenceReport": asset_descriptor(temporary, "convergence-report.json", "application/json")?,
            "coverageReport": asset_descriptor(temporary, "coverage-report.json", "application/json")?,
            "checksums": asset_descriptor(temporary, "checksums.json", "application/json")?,
        },
    });
    let identity_digest = {
        let mut identity = manifest.clone();
        let object = identity
            .as_object_mut()
            .ok_or_else(|| "manifest must be an object".to_owned())?;
        object.remove("datasetId");
        object
            .get_mut("contentAddressing")
            .and_then(Value::as_object_mut)
            .ok_or_else(|| "manifest contentAddressing is invalid".to_owned())?
            .remove("directoryName");
        hex(&digest(&canonical_json_bytes(&identity)?))
    };
    let manifest_object = manifest
        .as_object_mut()
        .ok_or_else(|| "manifest must be an object".to_owned())?;
    manifest_object.insert(
        "datasetId".to_owned(),
        Value::String(format!("sha256:{identity_digest}")),
    );
    manifest_object
        .get_mut("contentAddressing")
        .and_then(Value::as_object_mut)
        .ok_or_else(|| "manifest contentAddressing is invalid".to_owned())?
        .insert(
            "directoryName".to_owned(),
            Value::String(identity_digest.clone()),
        );
    write_json(temporary, "manifest.json", &manifest)?;

    let destination = output_root.join(&identity_digest);
    if destination.exists() {
        let existing_manifest = destination.join("manifest.json");
        if !existing_manifest.is_file()
            || fs::read(&existing_manifest)
                .map_err(|error| format!("unable to read existing manifest: {error}"))?
                != fs::read(temporary.join("manifest.json"))
                    .map_err(|error| format!("unable to read temporary manifest: {error}"))?
        {
            return Err(format!(
                "content-addressed destination exists with different content: {}",
                destination.display()
            ));
        }
        fs::remove_dir_all(temporary)
            .map_err(|error| format!("unable to remove duplicate temporary dataset: {error}"))?;
        return Ok(destination);
    }
    promote_directory(temporary, &destination)?;
    Ok(destination)
}

fn promote_directory(source: &Path, destination: &Path) -> Result<(), String> {
    const ATTEMPTS: u32 = 8;
    for attempt in 0..ATTEMPTS {
        match fs::rename(source, destination) {
            Ok(()) => return Ok(()),
            Err(error)
                if cfg!(windows)
                    && error.kind() == std::io::ErrorKind::PermissionDenied
                    && attempt + 1 < ATTEMPTS =>
            {
                // Managed Windows endpoint protection can hold a just-written
                // file briefly while scanning it. Retry the same atomic rename;
                // never fall back to a partially visible recursive copy.
                let delay_ms = 25_u64 << attempt.min(4);
                std::thread::sleep(Duration::from_millis(delay_ms));
            }
            Err(error) => {
                return Err(format!(
                    "unable to promote native dataset {}: {error}",
                    destination.display()
                ));
            }
        }
    }
    unreachable!("promotion loop returns on success or final failure")
}

fn foundation_coverage(modes: &[RuntimeMode], algorithm: &Algorithm) -> Value {
    let mut strongest = modes.iter().collect::<Vec<_>>();
    strongest.sort_by(|left, right| {
        let left = (left.actuator_coupling * left.microphone_coupling).abs();
        let right = (right.actuator_coupling * right.microphone_coupling).abs();
        right.partial_cmp(&left).unwrap_or(Ordering::Equal)
    });
    let outputs = (0..=100)
        .map(|target| {
            let anchor = strongest[target % strongest.len()];
            let fraction = target as f64 / 100.0;
            let dwell = if target == 0 {
                0.0
            } else {
                -(algorithm
                    .coverage_minimum_log_argument
                    .max(1.0 - algorithm.coverage_maximum_fraction * fraction))
                .ln()
                    / algorithm.coverage_capture_rate
            };
            let approach = if target % 2 == 0 { 1 } else { -1 };
            json!({
                "target": target,
                "verification": "candidate-requires-runtime-replay",
                "physicalAnchor": {
                    "modeId": anchor.mode_id,
                    "naturalFrequencyHz": anchor.natural_frequency_hz,
                    "approachDirection": approach,
                    "estimatedDwellSeconds": dwell,
                    "detuneRatio": (algorithm.coverage_base_detune
                        + algorithm.coverage_detune_step
                            * (target % algorithm.coverage_detune_cycle) as f64)
                        * approach as f64,
                },
            })
        })
        .collect::<Vec<_>>();
    json!({
        "schemaVersion": "mandelhowl.coverage-report.v2",
        "verificationStatus": "physics-foundation-only",
        "model": "global-exponential-modal-capture-seed-v1",
        "perValueRuntimeExceptionTable": false,
        "targetRange": [0, 100],
        "outputs": outputs,
        "releaseEligible": false,
        "note": "These are deterministic search seeds derived from baked mode coupling. A release bake must inject the runtime engine's replay-verified report with --coverage-report and --release.",
    })
}

pub(crate) fn expected_runtime_coverage_binding() -> Result<(String, Value, Value), String> {
    let repository = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let sources = [
        ("dial", "specs/runtime/dial.v1.yaml"),
        ("feedback", "specs/runtime/feedback.v1.yaml"),
        ("volumeMap", "specs/runtime/volume-map.v1.yaml"),
        ("audioSafety", "specs/runtime/audio-safety.v1.yaml"),
        ("uiNVersion", "specs/runtime/ui-nversion.v1.json"),
    ];
    let runtime_hashes = sources
        .iter()
        .map(|(key, relative)| {
            Ok((
                (*key).to_owned(),
                Value::String(file_sha256(&repository.join(relative))?),
            ))
        })
        .collect::<Result<std::collections::BTreeMap<_, _>, String>>()?;
    let feedback_source = fs::read_to_string(repository.join("specs/runtime/feedback.v1.yaml"))
        .map_err(|error| format!("unable to read canonical feedback spec: {error}"))?;
    let feedback = crate::yaml::parse(&feedback_source)
        .map_err(|error| format!("canonical feedback spec is invalid: {error}"))?;
    let runtime_revision = feedback
        .get("algorithmRevision")
        .and_then(Value::as_str)
        .ok_or_else(|| "canonical feedback algorithm revision is missing".to_owned())?
        .to_owned();
    let schema_path = repository.join("packages/contracts/schemas/coverage-report.schema.json");
    let coverage_contract = json!({
        "schemaVersion": "mandelhowl.coverage-report.v2",
        "schemaSha256": file_sha256(&schema_path)?,
    });
    Ok((
        runtime_revision,
        Value::Object(runtime_hashes),
        coverage_contract,
    ))
}

pub(crate) fn validate_external_coverage(
    report: &Value,
    release: bool,
    expected_modal_model_id: &str,
) -> Result<(), String> {
    let outputs = report
        .get("outputs")
        .and_then(Value::as_array)
        .ok_or_else(|| "coverage report must contain an outputs array".to_owned())?;
    let mut targets = outputs
        .iter()
        .map(|row| {
            row.get("target")
                .and_then(Value::as_u64)
                .ok_or_else(|| "coverage output target is invalid".to_owned())
        })
        .collect::<Result<Vec<_>, _>>()?;
    targets.sort_unstable();
    if targets != (0_u64..=100).collect::<Vec<_>>() {
        return Err(
            "coverage report must contain exactly one entry for every target 0..100".to_owned(),
        );
    }
    if report
        .get("perValueRuntimeExceptionTable")
        .and_then(Value::as_bool)
        != Some(false)
    {
        return Err("coverage report must explicitly deny per-value runtime exceptions".to_owned());
    }
    if release {
        let (runtime_revision, runtime_hashes, coverage_contract) =
            expected_runtime_coverage_binding()?;
        let generated_by = report
            .get("generatedBy")
            .ok_or_else(|| "release coverage generatedBy is missing".to_owned())?;
        let covered_values = report
            .get("coveredValues")
            .and_then(Value::as_array)
            .ok_or_else(|| "release coverage coveredValues are missing".to_owned())?;
        let missing_values = report
            .get("missingValues")
            .and_then(Value::as_array)
            .ok_or_else(|| "release coverage missingValues are missing".to_owned())?;
        if report.get("schemaVersion").and_then(Value::as_str)
            != Some("mandelhowl.coverage-report.v2")
            || report.get("modalModelId").and_then(Value::as_str) != Some(expected_modal_model_id)
            || report.get("verificationStatus").and_then(Value::as_str)
                != Some("runtime-replay-verified")
            || report
                .get("runtimeAlgorithmRevision")
                .and_then(Value::as_str)
                != Some(runtime_revision.as_str())
            || report.get("runtimeSpecSha256") != Some(&runtime_hashes)
            || report.get("coverageContract") != Some(&coverage_contract)
            || generated_by.get("algorithm").and_then(Value::as_str)
                != Some("deterministic-global-trajectory-search-v2")
            || generated_by
                .get("feedbackAlgorithmRevision")
                .and_then(Value::as_str)
                != Some(runtime_revision.as_str())
            || generated_by
                .get("perValueRuntimeLookup")
                .and_then(Value::as_str)
                != Some("forbidden")
            || generated_by.get("randomSource").and_then(Value::as_str) != Some("forbidden")
            || report.get("replayVerified").and_then(Value::as_bool) != Some(true)
            || covered_values.len() != 101
            || covered_values
                .iter()
                .enumerate()
                .any(|(index, value)| value.as_u64() != Some(index as u64))
            || !missing_values.is_empty()
        {
            return Err(
                "release coverage is not exactly bound to the generated modal model, runtime specs, runtime algorithm, and coverage schema".to_owned(),
            );
        }
        let traces = report
            .get("traces")
            .and_then(Value::as_array)
            .ok_or_else(|| "release coverage traces are missing".to_owned())?;
        if traces.len() != 101
            || traces.iter().any(|trace| {
                trace.get("modalModelId").and_then(Value::as_str) != Some(expected_modal_model_id)
            })
        {
            return Err("release coverage traces do not bind the generated modal model".to_owned());
        }
        let unverified = outputs.iter().filter(|row| {
            let target = row.get("target").and_then(Value::as_u64);
            row.get("verification").and_then(Value::as_str) != Some("runtime-replay-verified")
                || row.get("verified").and_then(Value::as_bool) != Some(true)
                || target
                    .and_then(|index| traces.get(index as usize))
                    .is_none_or(|trace| row.get("trace") != Some(trace))
        });
        if unverified.count() != 0 {
            return Err("release coverage has unverified targets".to_owned());
        }
    }
    Ok(())
}

fn field_statistics_json(statistics: &FieldStatistics) -> Value {
    json!({
        "analysisResolutionPx": statistics.analysis_resolution_px,
        "pixelPitchM": statistics.pixel_pitch_m,
        "filterRadiusPx": statistics.filter_radius_px,
        "manufacturingBevelPasses": statistics.manufacturing_bevel_passes,
        "actualMinimumFeatureM": statistics.actual_minimum_feature_m,
        "minimumFeatureMeasurement": "conservative close/open structuring-element diameter on the sampled field",
        "quantizationLevels": statistics.quantization_levels,
        "minimumThicknessM": statistics.minimum_thickness_m,
        "maximumThicknessM": statistics.maximum_thickness_m,
        "maximumThicknessGradient": statistics.maximum_thickness_gradient,
        "totalMassKg": statistics.total_mass_kg,
        "centreOfMassXM": statistics.centre_of_mass_x_m,
        "centreOfMassYM": statistics.centre_of_mass_y_m,
        "centreOfMassOffsetM": statistics.centre_of_mass_offset_m,
        "massWithinLimits": statistics.mass_within_limits,
        "centreOfMassWithinLimit": statistics.centre_of_mass_within_limit,
        "gradientWithinLimit": statistics.gradient_within_limit,
        "minimumThicknessWithinLimit": statistics.minimum_thickness_within_limit,
        "minimumFeatureWithinLimit": statistics.minimum_feature_within_limit,
    })
}

fn mode_summary(modes: &[RuntimeMode], index: usize) -> Value {
    let mode = &modes[index];
    let previous_spacing = if index == 0 {
        Value::Null
    } else {
        Value::Number(mode.natural_frequency_hz - modes[index - 1].natural_frequency_hz)
    };
    let next_spacing = if index + 1 == modes.len() {
        Value::Null
    } else {
        Value::Number(modes[index + 1].natural_frequency_hz - mode.natural_frequency_hz)
    };
    let nearest_spacing = match (previous_spacing.as_f64(), next_spacing.as_f64()) {
        (Some(previous), Some(next)) => Value::Number(previous.min(next)),
        (Some(previous), None) => Value::Number(previous),
        (None, Some(next)) => Value::Number(next),
        (None, None) => Value::Null,
    };
    json!({
        "modeId": mode.mode_id,
        "ordinal": mode.ordinal,
        "naturalFrequencyHz": mode.natural_frequency_hz,
        "angularFrequencyRadPerSecond": mode.angular_frequency_rad_per_s,
        "dampingRatio": mode.damping_ratio,
        "actuatorCoupling": mode.actuator_coupling,
        "microphoneCoupling": mode.microphone_coupling,
        "radiationEfficiency": mode.radiation_efficiency,
        "adjacentFrequencySpacingHz": {
            "previous": previous_spacing,
            "next": next_spacing,
            "nearest": nearest_spacing,
        },
        "surfaceKinematics": {
            "signedDisplacementTextureLayer": mode.texture_layer,
            "velocityScalePerUnitModalAmplitudePerSecond": mode.angular_frequency_rad_per_s,
            "velocityPhaseOffsetRad": std::f64::consts::FRAC_PI_2,
            "accelerationScalePerUnitModalAmplitudePerSecondSquared":
                mode.angular_frequency_rad_per_s * mode.angular_frequency_rad_per_s,
            "accelerationPhaseOffsetRad": std::f64::consts::PI,
        },
        "dominantBasis": {
            "radialNodeIndex": mode.dominant_radial_node_index,
            "radialDof": mode.dominant_radial_dof.as_str(),
            "angularOrder": mode.dominant_angular_order,
            "symmetry": mode.dominant_symmetry,
        },
        "signReference": mode.sign_reference,
        "textureLayer": mode.texture_layer,
    })
}

fn create_temporary_directory(output_root: &Path) -> Result<PathBuf, String> {
    for _ in 0..100 {
        let counter = TEMPORARY_COUNTER.fetch_add(1, AtomicOrdering::Relaxed);
        let path = output_root.join(format!(
            ".mandelhowl-native-bake-{}-{counter}",
            std::process::id()
        ));
        match fs::create_dir(&path) {
            Ok(()) => return Ok(path),
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => {
                return Err(format!(
                    "unable to create temporary dataset {}: {error}",
                    path.display()
                ));
            }
        }
    }
    Err("unable to allocate a unique native bake directory".to_owned())
}

fn write_bytes(root: &Path, relative: &str, bytes: &[u8]) -> Result<(), String> {
    let path = root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("unable to create {}: {error}", parent.display()))?;
    }
    fs::write(&path, bytes).map_err(|error| format!("unable to write {}: {error}", path.display()))
}

fn write_json(root: &Path, relative: &str, value: &Value) -> Result<(), String> {
    let mut bytes = crate::json::to_vec_pretty(value)
        .map_err(|error| format!("unable to serialize {relative}: {error}"))?;
    bytes.push(b'\n');
    write_bytes(root, relative, &bytes)
}

fn canonical_json_bytes(value: &Value) -> Result<Vec<u8>, String> {
    crate::json::to_vec(value).map_err(|error| format!("canonical JSON failed: {error}"))
}

fn asset_descriptor(root: &Path, relative: &str, media_type: &str) -> Result<Value, String> {
    let path = root.join(relative);
    Ok(json!({
        "path": relative.replace('\\', "/"),
        "byteLength": file_length(&path)?,
        "sha256": file_sha256(&path)?,
        "mediaType": media_type,
    }))
}

fn file_length(path: &Path) -> Result<u64, String> {
    fs::metadata(path)
        .map(|metadata| metadata.len())
        .map_err(|error| format!("unable to stat {}: {error}", path.display()))
}

fn file_sha256(path: &Path) -> Result<String, String> {
    let bytes =
        fs::read(path).map_err(|error| format!("unable to read {}: {error}", path.display()))?;
    Ok(hex(&digest(&bytes)))
}

fn inventory_paths(root: &Path) -> Result<Vec<PathBuf>, String> {
    fn visit(root: &Path, directory: &Path, output: &mut Vec<PathBuf>) -> Result<(), String> {
        for entry in fs::read_dir(directory)
            .map_err(|error| format!("unable to inventory {}: {error}", directory.display()))?
        {
            let entry = entry.map_err(|error| format!("unable to read inventory row: {error}"))?;
            let path = entry.path();
            if path.is_dir() {
                visit(root, &path, output)?;
            } else if path.is_file() {
                let relative = path
                    .strip_prefix(root)
                    .map_err(|_| "inventory path escaped dataset root".to_owned())?;
                let name = relative.file_name().and_then(|value| value.to_str());
                if !matches!(name, Some("manifest.json" | "checksums.json")) {
                    output.push(relative.to_path_buf());
                }
            }
        }
        Ok(())
    }
    let mut paths = Vec::new();
    visit(root, root, &mut paths)?;
    paths.sort_by_key(|path| normalize_relative(path));
    Ok(paths)
}

fn normalize_relative(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}
