export {
  advanceResonance,
  advanceResonanceScalars,
  classifyResonanceRegime,
  createResonanceState,
  estimateOpenLoopMarginAtFrequency,
  getResonanceSnapshot,
  initResonance,
  interpolateBakedFrequencyResponse,
  replaceResonanceDataset,
  resetResonanceAfterPausedGap,
  RUNTIME_FEEDBACK_ALGORITHM_REVISION,
  runtimeModalDatasetFromResonanceDataset,
  stepResonance,
  volumeFromVirtualRms,
  type CreateResonanceOptions,
  type InterpolatedFrequencyResponse,
  type ResonanceDrive,
  type ResonanceRegime,
  type ResonanceSnapshot,
  type ResonanceState,
  type RuntimeModalDataset,
  type RuntimeModalMode,
} from "./resonance-engine";
export {
  PROTOTYPE_MODAL_DATASET,
  type PrototypeModalDataset,
  type PrototypeModeRecord,
} from "./prototype-dataset";
export {
  advanceMandelHowlRuntime,
  advanceMandelHowlRuntimeInPlace,
  createMandelHowlRuntime,
  createRuntimeSnapshotWriter,
  dispatchRuntimeDial,
  getRuntimeSnapshot,
  replaceMandelHowlDataset,
  resetMandelHowlRuntimeAfterPausedGap,
} from "./runtime-engine";
export type {
  CreateMandelHowlRuntimeOptions,
  MandelHowlRuntimeState,
  RuntimeSnapshotConsumer,
  RuntimeSnapshotLease,
  RuntimeSnapshotRebuildReason,
  RuntimeSnapshotWriter,
} from "./runtime-engine";
